// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.EnumMap;
import java.util.Map;

public class Bank {

    //bank has infinite resources, but we track it
    private final Map<Resource, Integer> counts;

    public Bank() {
        counts = new EnumMap<>(Resource.class);
        for (Resource r : Resource.values()) {
            counts.put(r, 19);
        }
    }

    public boolean canGive(Resource r, int n) {
        if (r == null) {
            return true;
        }
        return counts.getOrDefault(r, 0) >= n;
    }

    public boolean give(Resource r, int n) {
        if (r == null) {
            return true;
        }
        if (!canGive(r, n)) {
            return false;
        }
        counts.put(r, counts.get(r) - n);
        return true;
    }

    public void receive(Resource r, int n) {
        if (r == null || n <= 0) {
            return;
        }
        counts.put(r, counts.getOrDefault(r, 0) + n);
    }


    
    public void receiveAll(Map<Resource, Integer> cards) {
        for (Map.Entry<Resource, Integer> entry : cards.entrySet()) {
            receive(entry.getKey(), entry.getValue());
        }
    }
}