// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

public class Board {
    private final Tile[] tiles = new Tile[19];
    private final Node[] nodes = new Node[54];
    private final List<Edge> edges = new ArrayList<>();
    private int robberTileId = 16;

    public final int[][] tileNodes = {

            //hard wire tileNodes, for each tile, we have their corresponding node identification number
            //the midde
            {0, 1, 2, 3, 4, 5},

            //inner ring
            {6, 7, 8, 9, 2, 1},
            {2, 9, 10, 11, 12, 3},
            {4, 3, 12, 13, 14, 15},
            {16, 5, 4, 15, 17, 18},
            {19, 20, 0, 5, 16, 21},
            {22, 23, 6, 1, 0, 20},

            //outer ring
            {24, 25, 26, 27, 8, 7},
            {8, 27, 28, 29, 10, 9},
            {10, 29, 30, 31, 32, 11},
            {12, 11, 32, 33, 34, 13},
            {14, 13, 34, 35, 36, 37},
            {17, 15, 14, 37, 38, 39},
            {40, 18, 17, 39, 41, 42},
            {43, 21, 16, 18, 40, 44},
            {47, 46, 19, 21, 43, 45},
            {48, 49, 22, 20, 19, 46},
            {50, 51, 52, 23, 22, 49},
            {52, 53, 24, 7, 6, 23}
    };

    public Board() {
        for (int i = 0; i < 54; i++) {
            nodes[i] = new Node(i);
        }

        //hard wiring the terrain tiles (numbers is the dice probabilities for tiles 0 to 18) then the corresponding fields
        Integer[] numbers = {10, 11, 8, 3, 11, 5, 12, 3, 6, 4, 6, 9, 5, 9, 8, 4, null, 2, 10};
        Terrain[] terrains = {
                Terrain.FOREST, Terrain.FIELDS, Terrain.HILLS, Terrain.MOUNTAINS, Terrain.PASTURE, Terrain.PASTURE,
                Terrain.PASTURE, Terrain.FIELDS, Terrain.MOUNTAINS, Terrain.FOREST, Terrain.MOUNTAINS, Terrain.FIELDS,
                Terrain.FOREST, Terrain.HILLS, Terrain.HILLS, Terrain.FIELDS, Terrain.DESERT, Terrain.FOREST, Terrain.PASTURE
        };



        for (int i = 0; i < 19; i++) {
            tiles[i] = new Tile(i, terrains[i], numbers[i]);
        }

        int edgeIdCounter = 0;
        for (int[] tNodes : tileNodes) {
            for (int i = 0; i < 6; i++) {
                int u = tNodes[i];
                int v = tNodes[(i + 1) % 6];
                if (getEdgeBetween(u, v) == null) {
                    edges.add(new Edge(edgeIdCounter++, u, v));
                }
            }
        }
    }

    public Tile tile(int tileId) {
        return tiles[tileId];
    }


    public Node node(int nodeId) {
        return nodes[nodeId];
    }

    public Edge edge(int edgeId) {
        return edges.get(edgeId);
    }

    public int[] nodesAroundTile(int tileId) {
        return tileNodes[tileId].clone();
    }

    public int robberTileId() {
        return robberTileId;
    }

    public void moveRobber(int tileId) {
        robberTileId = tileId;
    }


    public boolean tileBlockedByRobber(int tileId) {
        return robberTileId == tileId;
    }

    public Set<Integer> playersAdjacentToTile(int tileId) {
        Set<Integer> players = new LinkedHashSet<>();
        for (int nodeId : tileNodes[tileId]) {
            Node node = nodes[nodeId];
            if (!node.empty()) {
                players.add(node.getOwner());
            }
        }
        return players;
    }

    public int firstEmptyEdgeTouchingNode(int nodeId) {
        for (Edge edge : edges) {
            if (edge.empty() && (edge.getEndpoint1() == nodeId || edge.getEndpoint2() == nodeId)) {
                return edge.getId();
            }
        }
        return -1;
    }

    //this one can find the edge between 2 nodes
    public Edge getEdgeBetween(int u, int v) {
        for (Edge edge : edges) {
            if ((edge.getEndpoint1() == u && edge.getEndpoint2() == v)
                    || (edge.getEndpoint1() == v && edge.getEndpoint2() == u)) {
                return edge;
            }
        }
        return null;
    }

    private boolean endpointBlockedForRoadExtension(int nodeId, int playerId) {
        Node endpoint = node(nodeId);
        return !endpoint.empty() && endpoint.getOwner() != playerId;
    }

    private boolean hasConnectingRoadAtNode(int nodeId, int playerId) {
        if (endpointBlockedForRoadExtension(nodeId, playerId)) {
            return false;
        }
        for (Edge neighbor : edges) {
            if (neighbor.getRoadOwner() == playerId
                    && (neighbor.getEndpoint1() == nodeId || neighbor.getEndpoint2() == nodeId)) {
                return true;
            }
        }
        return false;
    }

    //legality logic, can they place a road?
	//implementing build legality checks
    public boolean canPlaceRoad(int playerId, int edgeId) {
        Edge candidate = edge(edgeId);
        if (!candidate.empty()) {
            return false;
        }

        int a = candidate.getEndpoint1();
        int b = candidate.getEndpoint2();
        boolean connectsToBuilding = node(a).getOwner() == playerId || node(b).getOwner() == playerId;
        boolean connectsToRoad = hasConnectingRoadAtNode(a, playerId) || hasConnectingRoadAtNode(b, playerId);
        return connectsToBuilding || connectsToRoad;
    }

    public boolean canPlaceSettlement(int playerId, int nodeId, Phase phase) {
        Node candidate = node(nodeId);
        if (!candidate.empty()) {
            return false;
        }


        for (Edge edge : edges) {
            if (edge.getEndpoint1() == nodeId || edge.getEndpoint2() == nodeId) {
                int neighborId = edge.getEndpoint1() == nodeId ? edge.getEndpoint2() : edge.getEndpoint1();
                if (!node(neighborId).empty()) {
                    return false;
                }
            }
        }

        if (phase == Phase.SETUP) {
            return true;
        }

        for (Edge edge : edges) {
            if (edge.getRoadOwner() == playerId
                    && (edge.getEndpoint1() == nodeId || edge.getEndpoint2() == nodeId)) {
                return true;
            }
        }
        return false;
    }

    public boolean canUpgradeToCity(int playerId, int nodeId) {
        Node candidate = node(nodeId);
        return candidate.getOwner() == playerId && candidate.getBuilding() == BuildingType.SETTLEMENT;
    }

    public void placeRoad(int playerId, int edgeId) {
        edge(edgeId).setRoadOwner(playerId);
    }


    public void placeSettlement(int playerId, int nodeId) {
        node(nodeId).setBuilding(playerId, BuildingType.SETTLEMENT);
    }

    public void upgradeToCity(int playerId, int nodeId) {
        node(nodeId).setBuilding(playerId, BuildingType.CITY);
    }

    public Node[] getNodes() {
        return nodes.clone();
    }


    public Tile[] getTiles() {
        return tiles.clone();
    }

    public List<Edge> getEdges() {
        return Collections.unmodifiableList(edges);
    }
}