// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class DicePair implements Dice {
    private final RegularDice die1;
    private final RegularDice die2;

    public DicePair() {
        this(new RegularDice(), new RegularDice());
    }

    public DicePair(RegularDice die1, RegularDice die2) {
        this.die1 = die1;
        this.die2 = die2;
    }

    @Override
    public int roll() {
        return die1.roll() + die2.roll();
    }
}