// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public interface PlayerController {
    void takeTurn(Game game, Player player);
}