// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class RandomAgentController implements PlayerController {
    private interface AgentMove {
        boolean execute();
    }

    private final Random random;

    public RandomAgentController() {
        this(new Random());
    }

    public RandomAgentController(Random random) {
        this.random = random;
    }

    @Override
    public void takeTurn(Game game, Player player) {
        game.performRoll(player);

        while (player.totalCards() > 7) {
            List<AgentMove> legalMoves = collectLegalMoves(game, player);
            if (legalMoves.isEmpty()) {
                break;
            }
            legalMoves.get(random.nextInt(legalMoves.size())).execute();
        }

        if (player.totalCards() <= 7) {
            List<AgentMove> legalMoves = collectLegalMoves(game, player);
            if (!legalMoves.isEmpty() && random.nextDouble() < 0.70) {
                legalMoves.get(random.nextInt(legalMoves.size())).execute();
            }
        }

        game.log(player, "Go.");
    }

    private List<AgentMove> collectLegalMoves(Game game, Player player) {
        List<AgentMove> legalMoves = new ArrayList<>();

        if (player.getCitiesLeft() > 0 && player.hasResources(Game.CITY_COST)) {
            for (Node node : game.board().getNodes()) {
                final int nodeId = node.getId();
                if (game.board().canUpgradeToCity(player.id(), nodeId)) {
                    legalMoves.add(() -> game.upgradeToCity(player, nodeId));
                }
            }
        }

        if (player.getSettlementsLeft() > 0 && player.hasResources(Game.SETTLEMENT_COST)) {
            for (int nodeId = 0; nodeId < game.board().getNodes().length; nodeId++) {
                final int candidateNodeId = nodeId;
                if (game.board().canPlaceSettlement(player.id(), candidateNodeId, game.phase())) {
                    legalMoves.add(() -> game.buildSettlement(player, candidateNodeId));
                }
            }
        }

        if (player.getRoadsLeft() > 0 && player.hasResources(Game.ROAD_COST)) {
            for (Edge edge : game.board().getEdges()) {
                final int edgeId = edge.getId();
                if (game.board().canPlaceRoad(player.id(), edgeId)) {
                    legalMoves.add(() -> game.buildRoad(player, edgeId));
                }
            }
        }

        return legalMoves;
    }
}