// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class RollCommand implements HumanCommand {
    @Override
    public boolean execute(Game game, Player player) {
        return game.performRoll(player);
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}