// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;
public class StepController {
    private final CommandLineUI ui;
    private final boolean enabled;

    public StepController(CommandLineUI ui, boolean enabled) {
        this.ui = ui;
        this.enabled = enabled;
    }

    public void awaitGo(String prompt) {
        if (!enabled) {
            return;
        }


        while (true) {
            ui.printLine(prompt);
            String raw = ui.readLine();
            if (raw != null && raw.trim().equalsIgnoreCase("go")) {
                return;
            }
            ui.printLine("Please type 'go' to continue.");
        }
    }
}