// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class Tile {
    private final int id;
    private final Terrain terrain;
    private final Integer number;

    public Tile(int id, Terrain terrain, Integer number) {
        this.id = id;
        this.terrain = terrain;
        this.number = number;
    }

    public Resource getResource() {
        switch (terrain) {
            case FOREST: return Resource.WOOD;
            case HILLS: return Resource.BRICK;
            case FIELDS: return Resource.WHEAT;
            case PASTURE: return Resource.SHEEP;
            case MOUNTAINS: return Resource.ORE;
            default: return null;
        }
    }

    public int getId() {
        return id;
    }

    public Terrain getTerrain() {
        return terrain;
    }

    public Integer getNumber() {
        return number;
    }
}