// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class TurnManager {
    private int current = 0;
    private Phase phase = Phase.SETUP;
    private TurnStage stage = TurnStage.SETUP_SETTLEMENT;

    public int currentPlayerIndex() {
        return current;
    }

    public Phase phase() {
        return phase;
    }

    public TurnStage stage() {
        return stage;
    }

    public void nextTurn(int nPlayers) {
        current = (current + 1) % nPlayers;
    }

    public void setPhase(Phase phase) {
        this.phase = phase;
    }

    public void setStage(TurnStage stage) {
        this.stage = stage;
    }
}