// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.List;
import java.util.Map;
import java.util.Random;

public abstract class AbstractAgentRule {
    private final Random random;

    protected AbstractAgentRule(Random random) {
        this.random = random;
    }

    public final RuleEvaluation evaluateRule(Game game, Player player) {
        List<Integer> legalTargets = collectLegalTargets(game, player);
        if (legalTargets.isEmpty()) {
            return null;
        }

        int targetId = legalTargets.get(random.nextInt(legalTargets.size()));
        return new RuleEvaluation(this, targetId, computeImmediateValue(player));
    }

    public final boolean executeRule(Game game, Player player, int targetId) {
        return applyRule(game, player, targetId);
    }

    private double computeImmediateValue(Player player) {
        double value = 0.0;

        if (cardsRemainingAfterSpend(player) < 5) {
            value = 0.5;
        }
        if (buildsWithoutVictoryPoint()) {
            value = Math.max(value, 0.8);
        }
        if (earnsVictoryPoint()) {
            value = Math.max(value, 1.0);
        }

        return value;
    }

    private int cardsRemainingAfterSpend(Player player) {
        int spent = 0;
        for (int amount : getCost().values()) {
            spent += amount;
        }
        return player.totalCards() - spent;
    }

    protected abstract List<Integer> collectLegalTargets(Game game, Player player);

    protected abstract boolean applyRule(Game game, Player player, int targetId);

    protected abstract Map<Resource, Integer> getCost();

    protected abstract boolean earnsVictoryPoint();

    protected abstract boolean buildsWithoutVictoryPoint();

    public abstract String name();
}