// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public abstract class AbstractConstraintHandler {
    private AbstractConstraintHandler next;

    public AbstractConstraintHandler setNext(AbstractConstraintHandler next) {
        this.next = next;
        return next;
    }

    public final boolean handle(Game game, Player player) {
        if (tryHandle(game, player)) {
            return true;
        }
        return next != null && next.handle(game, player);
    }

    protected abstract boolean tryHandle(Game game, Player player);
}