// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class BuildCityCommand extends AbstractUndoableCommand {
    private final int nodeId;

    public BuildCityCommand(int nodeId) {
        this.nodeId = nodeId;
    }

    public int getNodeId() {
        return nodeId;
    }

    @Override
    protected boolean executeCommand(Game game, Player player) {
        if (game.phase() == Phase.SETUP) {
            game.systemMessage("Cities cannot be built during setup.");
            return false;
        }
        return game.upgradeToCity(player, nodeId);
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}