// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class BuildCityRule extends AbstractAgentRule {
    public BuildCityRule(Random random) {
        super(random);
    }

    @Override
    protected List<Integer> collectLegalTargets(Game game, Player player) {
        List<Integer> legalTargets = new ArrayList<>();
        if (player.getCitiesLeft() <= 0 || !player.hasResources(Game.CITY_COST)) {
            return legalTargets;
        }

        for (Node node : game.board().getNodes()) {
            int nodeId = node.getId();
            if (game.board().canUpgradeToCity(player.id(), nodeId)) {
                legalTargets.add(nodeId);
            }
        }
        return legalTargets;
    }

    @Override
    protected boolean applyRule(Game game, Player player, int targetId) {
        return game.upgradeToCity(player, targetId);
    }

    @Override
    protected Map<Resource, Integer> getCost() {
        return Game.CITY_COST;
    }

    @Override
    protected boolean earnsVictoryPoint() {
        return true;
    }

    @Override
    protected boolean buildsWithoutVictoryPoint() {
        return false;
    }

    @Override
    public String name() {
        return "BuildCityRule";
    }
}