// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class BuildRoadRule extends AbstractAgentRule {
    public BuildRoadRule(Random random) {
        super(random);
    }

    @Override
    protected List<Integer> collectLegalTargets(Game game, Player player) {
        List<Integer> legalTargets = new ArrayList<>();
        if (player.getRoadsLeft() <= 0 || !player.hasResources(Game.ROAD_COST)) {
            return legalTargets;
        }

        for (Edge edge : game.board().getEdges()) {
            int edgeId = edge.getId();
            if (game.board().canPlaceRoad(player.id(), edgeId)) {
                legalTargets.add(edgeId);
            }
        }
        return legalTargets;
    }

    @Override
    protected boolean applyRule(Game game, Player player, int targetId) {
        return game.buildRoad(player, targetId);
    }

    @Override
    protected Map<Resource, Integer> getCost() {
        return Game.ROAD_COST;
    }

    @Override
    protected boolean earnsVictoryPoint() {
        return false;
    }

    @Override
    protected boolean buildsWithoutVictoryPoint() {
        return true;
    }

    @Override
    public String name() {
        return "BuildRoadRule";
    }
}