// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class BuildSettlementRule extends AbstractAgentRule {
    public BuildSettlementRule(Random random) {
        super(random);
    }

    @Override
    protected List<Integer> collectLegalTargets(Game game, Player player) {
        List<Integer> legalTargets = new ArrayList<>();
        if (player.getSettlementsLeft() <= 0 || !player.hasResources(Game.SETTLEMENT_COST)) {
            return legalTargets;
        }

        for (int nodeId = 0; nodeId < game.board().getNodes().length; nodeId++) {
            if (game.board().canPlaceSettlement(player.id(), nodeId, game.phase())) {
                legalTargets.add(nodeId);
            }
        }
        return legalTargets;
    }

    @Override
    protected boolean applyRule(Game game, Player player, int targetId) {
        return game.buildSettlement(player, targetId);
    }

    @Override
    protected Map<Resource, Integer> getCost() {
        return Game.SETTLEMENT_COST;
    }

    @Override
    protected boolean earnsVictoryPoint() {
        return true;
    }

    @Override
    protected boolean buildsWithoutVictoryPoint() {
        return false;
    }

    @Override
    public String name() {
        return "BuildSettlementRule";
    }
}