// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class ConnectRoadSegmentsConstraintHandler extends AbstractConstraintHandler {
    @Override
    protected boolean tryHandle(Game game, Player player) {
        if (player.getRoadsLeft() <= 0 || !player.hasResources(Game.ROAD_COST)) {
            return false;
        }

        int edgeId = game.board().findRoadConnectionEdge(player.id());
        if (edgeId == -1) {
            return false;
        }
        return game.buildRoad(player, edgeId);
    }
}