// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.Scanner;

public class ConsoleUI implements CommandLineUI {
    private final Scanner scanner;

    public ConsoleUI() {
        this(new Scanner(System.in));
    }

    public ConsoleUI(Scanner scanner) {
        this.scanner = scanner;
    }

    @Override
    public String readLine() {
        return scanner.nextLine();
    }

    @Override
    public void printLine(String message) {
        System.out.println(message);
    }
}