// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.EnumMap;
import java.util.Map;

public class GameSnapshot {

    public static class PlayerState {
        private final Map<Resource, Integer> hand;
        private final int roadsLeft;
        private final int settlementsLeft;
        private final int citiesLeft;
        private final int victoryPoints;

        public PlayerState(Map<Resource, Integer> hand, int roadsLeft, int settlementsLeft, int citiesLeft, int victoryPoints) {
            this.hand = new EnumMap<>(Resource.class);
            this.hand.putAll(hand);
            this.roadsLeft = roadsLeft;
            this.settlementsLeft = settlementsLeft;
            this.citiesLeft = citiesLeft;
            this.victoryPoints = victoryPoints;
        }

        public Map<Resource, Integer> hand() {
            Map<Resource, Integer> copy = new EnumMap<>(Resource.class);
            copy.putAll(hand);
            return copy;
        }

        public int roadsLeft() {
            return roadsLeft;
        }

        public int settlementsLeft() {
            return settlementsLeft;
        }

        public int citiesLeft() {
            return citiesLeft;
        }

        public int victoryPoints() {
            return victoryPoints;
        }
    }

    private final PlayerState[] playerStates;
    private final Map<Resource, Integer> bankCounts;
    private final int[] nodeOwners;
    private final BuildingType[] nodeBuildings;
    private final int[] edgeOwners;
    private final int robberTileId;
    private final int currentPlayerIndex;
    private final Phase phase;
    private final TurnStage stage;
    private final int turnId;

    public GameSnapshot(PlayerState[] playerStates,
                        Map<Resource, Integer> bankCounts,
                        int[] nodeOwners,
                        BuildingType[] nodeBuildings,
                        int[] edgeOwners,
                        int robberTileId,
                        int currentPlayerIndex,
                        Phase phase,
                        TurnStage stage,
                        int turnId) {
        this.playerStates = playerStates.clone();

        this.bankCounts = new EnumMap<>(Resource.class);
        this.bankCounts.putAll(bankCounts);

        this.nodeOwners = nodeOwners.clone();
        this.nodeBuildings = nodeBuildings.clone();
        this.edgeOwners = edgeOwners.clone();
        this.robberTileId = robberTileId;
        this.currentPlayerIndex = currentPlayerIndex;
        this.phase = phase;
        this.stage = stage;
        this.turnId = turnId;
    }

    public PlayerState[] playerStates() {
        return playerStates.clone();
    }

    public Map<Resource, Integer> bankCounts() {
        Map<Resource, Integer> copy = new EnumMap<>(Resource.class);
        copy.putAll(bankCounts);
        return copy;
    }

    public int[] nodeOwners() {
        return nodeOwners.clone();
    }

    public BuildingType[] nodeBuildings() {
        return nodeBuildings.clone();
    }

    public int[] edgeOwners() {
        return edgeOwners.clone();
    }

    public int robberTileId() {
        return robberTileId;
    }

    public int currentPlayerIndex() {
        return currentPlayerIndex;
    }

    public Phase phase() {
        return phase;
    }

    public TurnStage stage() {
        return stage;
    }

    public int turnId() {
        return turnId;
    }
}