// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class GameConfig {
    private static final Pattern TURNS = Pattern.compile("^\\s*turns\\s*:\\s*(\\d+)\\s*$", Pattern.CASE_INSENSITIVE | Pattern.MULTILINE);

    private final int turns;

    public GameConfig(int turns) {
        if (turns < 1 || turns > 8192) {
            throw new IllegalArgumentException("turns must be between 1 and 8192 inclusive.");
        }
        this.turns = turns;
    }

    public int turns() {
        return turns;
    }


    
    public static GameConfig load(String path) {
        try {
            String raw = Files.readString(Path.of(path));
            Matcher matcher = TURNS.matcher(raw);
            if (!matcher.find()) {
                throw new IllegalArgumentException("Config must contain: turns: <int>");
            }
            return new GameConfig(Integer.parseInt(matcher.group(1)));
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to read config file: " + path, ex);
        }
    }
}