// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class GoCommand implements HumanCommand {
    @Override
    public boolean execute(Game game, Player player) {
        
        if (game.phase() == Phase.MAIN && game.stage() == TurnStage.WAIT_ROLL) {
            game.systemMessage("You must roll before ending your turn.");
            return false;
        }
        game.log(player, "Go.");
        return true;

    }


    @Override
    public boolean endsTurn() {
        return true;
    }
}