// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public interface HumanCommand {
    boolean execute(Game game, Player player);
    boolean endsTurn();
}