// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

public class JsonGameStateWriter implements GameStateWriter {
    private final Path outputPath;

    public JsonGameStateWriter(String outputPath) {
        this.outputPath = Path.of(outputPath);
    }

    @Override
    public void write(Game game) {
        StringBuilder json = new StringBuilder();
        json.append("{\n  \"roads\": [\n");

        List<String> roadLines = new ArrayList<>();
        for (Edge edge : game.board().getEdges()) {
            if (!edge.empty()) {
                String owner = game.players()[edge.getRoadOwner()].color().name();
                roadLines.add(String.format("    { \"a\": %d, \"b\": %d, \"owner\": \"%s\" }",
                        edge.getEndpoint1(), edge.getEndpoint2(), owner));
            }
        }
        json.append(String.join(",\n", roadLines));
        json.append("\n  ],\n  \"buildings\": [\n");

        List<String> buildingLines = new ArrayList<>();
        for (Node node : game.board().getNodes()) {
            if (!node.empty()) {
                String owner = game.players()[node.getOwner()].color().name();
                String type = node.getBuilding().name();
                buildingLines.add(String.format("    { \"node\": %d, \"owner\": \"%s\", \"type\": \"%s\" }",
                        node.getId(), owner, type));
            }
        }
        json.append(String.join(",\n", buildingLines));
        json.append("\n  ]\n}\n");

        try {
            Files.writeString(outputPath, json.toString(), StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to write game state JSON to " + outputPath, ex);
        }
    }
}