// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public enum PlayerColor {
    RED,
    BLUE,
    ORANGE,
    WHITE
}