// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class RandomAgentController implements PlayerController {
    private final Random random;
    private final List<AbstractAgentRule> rules;
    private final AbstractConstraintHandler constraintChain;

    public RandomAgentController() {
        this(new Random());
    }

    public RandomAgentController(Random random) {
        this.random = random;
        this.rules = new ArrayList<>();
        this.rules.add(new BuildCityRule(random));
        this.rules.add(new BuildSettlementRule(random));
        this.rules.add(new BuildRoadRule(random));
        this.constraintChain = createConstraintChain();
    }


    private AbstractConstraintHandler createConstraintChain() {
        AbstractConstraintHandler spendCards = new SpendCardsConstraintHandler(rules, random);
        AbstractConstraintHandler connectRoadSegments = new ConnectRoadSegmentsConstraintHandler();
        AbstractConstraintHandler defendLongestRoad = new DefendLongestRoadConstraintHandler();

        spendCards.setNext(connectRoadSegments).setNext(defendLongestRoad);
        return spendCards;
    }

    @Override
    public void takeTurn(Game game, Player player) {
        if (!game.performRoll(player)) {
            return;
        }

        while (constraintChain.handle(game, player)) {
            //resolve all constraints before normal value based rules
        }

        RuleEvaluation evaluation = chooseBestRule(game, player);
        if (evaluation != null) {
            evaluation.rule().executeRule(game, player, evaluation.targetId());
        }

        game.log(player, "Go.");
    }

    
    private RuleEvaluation chooseBestRule(Game game, Player player) {
        List<RuleEvaluation> bestEvaluations = new ArrayList<>();
        double bestValue = -1.0;

        for (AbstractAgentRule rule : rules) {
            RuleEvaluation evaluation = rule.evaluateRule(game, player);
            if (evaluation == null) {
                continue;
            }

            if (evaluation.value() > bestValue) {
                bestEvaluations.clear();
                bestEvaluations.add(evaluation);
                bestValue = evaluation.value();
            } 
            else if (Double.compare(evaluation.value(), bestValue) == 0) {
                bestEvaluations.add(evaluation);
            }
        }

        if (bestEvaluations.isEmpty()) {
            return null;
        }
        return bestEvaluations.get(random.nextInt(bestEvaluations.size()));
    }

}