// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
import java.util.Random;

public class RegularDice implements Dice {
    private final Random rand;

    public RegularDice() {
        this(new Random());
    }

    public RegularDice(Random rand) {
        this.rand = rand;
    }

    @Override
    public int roll() {
        return rand.nextInt(6) + 1;
    }
}