// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class RollCommand extends AbstractUndoableCommand {
    @Override
    protected boolean executeCommand(Game game, Player player) {
        return game.performRoll(player);
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}