// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class RuleEvaluation {
    private final AbstractAgentRule rule;
    private final int targetId;
    private final double value;

    public RuleEvaluation(AbstractAgentRule rule, int targetId, double value) {
        this.rule = rule;
        this.targetId = targetId;
        this.value = value;
    }

    public AbstractAgentRule rule() {
        return rule;
    }

    public int targetId() {
        return targetId;
    }

    public double value() {
        return value;
    }
}