// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class SpendCardsConstraintHandler extends AbstractConstraintHandler {
    private final List<AbstractAgentRule> rules;
    private final Random random;

    public SpendCardsConstraintHandler(List<AbstractAgentRule> rules, Random random) {
        this.rules = new ArrayList<>(rules);
        this.random = random;
    }

    @Override
    protected boolean tryHandle(Game game, Player player) {
        if (player.totalCards() <= 7) {
            return false;
        }

        RuleEvaluation evaluation = chooseBestRule(game, player);
        return evaluation != null && evaluation.rule().executeRule(game, player, evaluation.targetId());
    }

    private RuleEvaluation chooseBestRule(Game game, Player player) {
        List<RuleEvaluation> bestEvaluations = new ArrayList<>();
        double bestValue = -1.0;

        for (AbstractAgentRule rule : rules) {
            RuleEvaluation evaluation = rule.evaluateRule(game, player);
            if (evaluation == null) {
                continue;
            }

            if (evaluation.value() > bestValue) {
                bestEvaluations.clear();
                bestEvaluations.add(evaluation);
                bestValue = evaluation.value();
            } else if (Double.compare(evaluation.value(), bestValue) == 0) {
                bestEvaluations.add(evaluation);
            }
        }

        if (bestEvaluations.isEmpty()) {
            return null;
        }
        return bestEvaluations.get(random.nextInt(bestEvaluations.size()));
    }
}