// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public enum TurnStage {
    SETUP_SETTLEMENT,
    SETUP_ROAD,
    WAIT_ROLL,
    ACTIONS
}