// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public interface UndoableCommand extends HumanCommand {
    void undo(Game game);
    void redo(Game game);
}