// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class UndoCommand implements HumanCommand {
    private final CommandHistory history;

    public UndoCommand(CommandHistory history) {
        this.history = history;
    }

    @Override
    public boolean execute(Game game, Player player) {
        return history.undo(game);
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}