// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public abstract class AbstractUndoableCommand implements UndoableCommand {
    private GameSnapshot beforeState;
    private GameSnapshot afterState;

    @Override
    public final boolean execute(Game game, Player player) {
        beforeState = game.createSnapshot();
        boolean success = executeCommand(game, player);
        if (!success) {
            beforeState = null;
            afterState = null;
            return false;
        }
        afterState = game.createSnapshot();
        return true;
    }

    protected abstract boolean executeCommand(Game game, Player player);

    @Override
    public void undo(Game game) {
        if (beforeState == null) {
            return;
        }
        game.restoreSnapshot(beforeState);
        game.writeGameState();
        game.systemMessage("Undo successful.");
    }

    @Override
    public void redo(Game game) {
        if (afterState == null) {
            return;
        }
        game.restoreSnapshot(afterState);
        game.writeGameState();
        game.systemMessage("Redo successful.");
    }
}