// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class BuildRoadCommand implements HumanCommand {
    private final int fromNodeId;
    private final int toNodeId;

    public BuildRoadCommand(int fromNodeId, int toNodeId) {
        this.fromNodeId = fromNodeId;
        this.toNodeId = toNodeId;
    }

    
    public int getFromNodeId() {
        return fromNodeId;
    }

    public int getToNodeId() {
        return toNodeId;
    }

    @Override
    public boolean execute(Game game, Player player) {


        if (game.phase() == Phase.SETUP) {
            game.systemMessage("Use setup prompts to place your opening road.");
            return false;
        }
        return game.buildRoadBetweenNodes(player, fromNodeId, toNodeId);
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}