// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class BuildSettlementCommand implements HumanCommand {
    private final int nodeId;

    public BuildSettlementCommand(int nodeId) {
        this.nodeId = nodeId;
    }

    public int getNodeId() {
        return nodeId;
    }

    @Override
    public boolean execute(Game game, Player player) {
        if (game.phase() == Phase.SETUP) {
            game.systemMessage("Use setup prompts to place your opening settlement.");
            return false;
        }
        return game.buildSettlement(player, nodeId);
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}