// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public interface CommandLineUI {
    String readLine();
    void printLine(String message);
}