// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayDeque;
import java.util.Deque;

public class CommandHistory {
    private final Deque<UndoableCommand> undoStack = new ArrayDeque<>();
    private final Deque<UndoableCommand> redoStack = new ArrayDeque<>();

    public void record(UndoableCommand command) {
        undoStack.push(command);
        redoStack.clear();
    }

    public boolean undo(Game game) {
        if (undoStack.isEmpty()) {
            game.systemMessage("Nothing to undo.");
            return false;
        }

        UndoableCommand command = undoStack.pop();
        command.undo(game);
        redoStack.push(command);
        return true;
    }

    public boolean redo(Game game) {
        if (redoStack.isEmpty()) {
            game.systemMessage("Nothing to redo.");
            return false;
        }

        UndoableCommand command = redoStack.pop();
        command.redo(game);
        undoStack.push(command);
        return true;
    }

    public void clear() {
        undoStack.clear();
        redoStack.clear();
    }
}