// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class CommandParser {
    private static final Pattern ROLL = Pattern.compile("^\\s*roll\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern GO = Pattern.compile("^\\s*go\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern LIST = Pattern.compile("^\\s*list\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern UNDO = Pattern.compile("^\\s*undo\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern REDO = Pattern.compile("^\\s*redo\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern BUILD_SETTLEMENT = Pattern.compile("^\\s*build\\s+settlement\\s+\\[?\\s*(\\d+)\\s*]?\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern BUILD_CITY = Pattern.compile("^\\s*build\\s+city\\s+\\[?\\s*(\\d+)\\s*]?\\s*$", Pattern.CASE_INSENSITIVE);
    private static final Pattern BUILD_ROAD = Pattern.compile("^\\s*build\\s+road\\s+\\[?\\s*(\\d+)\\s*,\\s*(\\d+)\\s*]?\\s*$", Pattern.CASE_INSENSITIVE);

    public HumanCommand parse(String raw) {
        return parse(raw, null);
    }

    public HumanCommand parse(String raw, CommandHistory history) {
        if (raw == null) {
            throw new IllegalArgumentException("Command cannot be null.");
        }
        Matcher matcher;
        if (ROLL.matcher(raw).matches()) {
            return new RollCommand();
        }
        if (GO.matcher(raw).matches()) {
            return new GoCommand();
        }
        if (LIST.matcher(raw).matches()) {
            return new ListCommand();
        }
        if (UNDO.matcher(raw).matches()) {
            if (history == null) {
                throw new IllegalArgumentException("Undo is not available right now.");
            }
            return new UndoCommand(history);
        }
        if (REDO.matcher(raw).matches()) {
            if (history == null) {
                throw new IllegalArgumentException("Redo is not available right now.");
            }
            return new RedoCommand(history);
        }

        matcher = BUILD_SETTLEMENT.matcher(raw);
        if (matcher.matches()) {
            return new BuildSettlementCommand(Integer.parseInt(matcher.group(1)));
        }

        matcher = BUILD_CITY.matcher(raw);
        if (matcher.matches()) {
            return new BuildCityCommand(Integer.parseInt(matcher.group(1)));
        }
        matcher = BUILD_ROAD.matcher(raw);
        if (matcher.matches()) {
            return new BuildRoadCommand(Integer.parseInt(matcher.group(1)), Integer.parseInt(matcher.group(2)));
        }
        throw new IllegalArgumentException("Invalid command: " + raw);
    }
}