// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class DefendLongestRoadConstraintHandler extends AbstractConstraintHandler {
    @Override
    protected boolean tryHandle(Game game, Player player) {
        if (player.getRoadsLeft() <= 0 || !player.hasResources(Game.ROAD_COST)) {
            return false;
        }

        int ownLongestRoad = game.board().longestRoadLength(player.id());
        if (ownLongestRoad == 0) {
            return false;
        }

        for (Player other : game.players()) {
            if (other.id() == player.id()) {
                continue;
            }
            if (game.board().longestRoadLength(other.id()) >= ownLongestRoad - 1) {
                int edgeId = game.board().firstConnectedRoadEdge(player.id());
                if (edgeId != -1) {
                    return game.buildRoad(player, edgeId);
                }
                return false;
            }
        }
        return false;
    }
}