// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;

public class Game {
    public static final Map<Resource, Integer> ROAD_COST = Map.of(Resource.BRICK, 1, Resource.WOOD, 1);
    public static final Map<Resource, Integer> SETTLEMENT_COST = Map.of(Resource.BRICK, 1,Resource.WOOD, 1,Resource.WHEAT, 1,Resource.SHEEP, 1);
    public static final Map<Resource, Integer> CITY_COST = Map.of(Resource.ORE, 3, Resource.WHEAT, 2);

    private final Board board;
    private final Bank bank;
    private final TurnManager turns;
    private final Dice dice;
    private final Player[] players;
    private final PlayerController[] controllers;
    private final GameStateWriter stateWriter;
    private final StepController stepper;
    private final Random random;
    private int turnId = 1;

    public Game(Board board,
                Bank bank,
                TurnManager turns,
                Dice dice,
                Player[] players,
                PlayerController[] controllers,
                GameStateWriter stateWriter,
                StepController stepper,
                Random random) {
        this.board = board;
        this.bank = bank;
        this.turns = turns;
        this.dice = dice;
        this.players = players;
        this.controllers = controllers;
        this.stateWriter = stateWriter;
        this.stepper = stepper;
        this.random = random;
    }

    public Board board() {
        return board;
    }

    public Phase phase() {
        return turns.phase();
    }

    public TurnStage stage() {
        return turns.stage();
    }


    public Player[] players() {
        return players.clone();
    }

    public Player currentPlayer() {
        return players[turns.currentPlayerIndex()];
    }

    public void systemMessage(String message) {
        System.out.println("[SYSTEM]: " + message);
    }

    public void log(Player player, String action) {
        System.out.println("[" + turnId + "] / [P" + player.id() + "]: " + action);
    }

    public void run(int maxRounds) {
        setupPhase();
        turns.setPhase(Phase.MAIN);
        turns.setStage(TurnStage.WAIT_ROLL);
        writeGameState();


        int completedRounds = 0;
        while (completedRounds < maxRounds) {
            Player current = currentPlayer();
            PlayerController controller = controllers[current.id()];

            if (!(controller instanceof HumanController) && hasHumanPlayer()) {
                stepper.awaitGo("Type 'go' to proceed to the next agent turn.");
            }


            controller.takeTurn(this, current);
            writeGameState();

            if (current.vp() >= 10) {
                log(current, "Wins with " + current.vp() + " VP.");
                return;
            }

            if (turns.currentPlayerIndex() == players.length - 1) {
                completedRounds++;
                printRoundSummary(completedRounds);
            }



            if (completedRounds >= maxRounds) {
                break;
            }


            turns.nextTurn(players.length);
            turns.setStage(TurnStage.WAIT_ROLL);
            turnId++;
        }
    }

    private boolean hasHumanPlayer() {
        for (PlayerController controller : controllers) {
            if (controller instanceof HumanController) {
                return true;
            }
        }
        return false;
    }

    private void printRoundSummary(int roundNumber) {
        StringBuilder summary = new StringBuilder();
        summary.append("Round ").append(roundNumber).append(" VP Summary: ");
        for (Player player : players) {
            summary.append("P").append(player.id()).append("=").append(player.vp()).append(" ");
        }
        System.out.println(summary.toString().trim());
    }


    private void setupPhase() {
        int[] order = {0, 1, 2, 3, 3, 2, 1, 0};
        for (int i = 0; i < order.length; i++) {
            int playerId = order[i];
            Player player = players[playerId];
            int nodeId;
            int edgeId;

            turns.setStage(TurnStage.SETUP_SETTLEMENT);
            if (controllers[playerId] instanceof HumanController) {
                nodeId = performHumanSetupSettlement(player, (HumanController) controllers[playerId]);
            } else {
                nodeId = pickRandomSetupSettlement(playerId);
                setupPlaceSettlement(player, nodeId);
                log(player, "Setup settlement at node " + nodeId + ".");
            }

            turns.setStage(TurnStage.SETUP_ROAD);
            if (controllers[playerId] instanceof HumanController) {
                edgeId = performHumanSetupRoad(player, nodeId, (HumanController) controllers[playerId]);
            } else {
                edgeId = board.firstEmptyEdgeTouchingNode(nodeId);
                setupPlaceRoad(player, edgeId);
                log(player, "Setup road at edge " + edgeId + ".");
            }

            if (i >= 4) {
                grantInitialResourcesFromNode(playerId, nodeId);
            }
            writeGameState();
        }
    }



    private int performHumanSetupSettlement(Player player, HumanController controller) {
        controller.ui().printLine("Setup: Build settlement <nodeId>");
        while (true) {
            String raw = controller.ui().readLine();
            try {
                HumanCommand command = controller.parser().parse(raw);
                if (command instanceof BuildSettlementCommand) {
                    int nodeId = ((BuildSettlementCommand) command).getNodeId();
                    if (board.canPlaceSettlement(player.id(), nodeId, Phase.SETUP)) {
                        setupPlaceSettlement(player, nodeId);
                        log(player, "Setup settlement at node " + nodeId + ".");
                        return nodeId;
                    }
                }
            } catch (IllegalArgumentException ex) {
                controller.ui().printLine(ex.getMessage());
            }
            controller.ui().printLine("Invalid setup settlement. Try again.");
        }
    }


    private int performHumanSetupRoad(Player player, int settlementNodeId, HumanController controller) {
        controller.ui().printLine("Setup: Build road [fromNodeId, toNodeId]");
        while (true) {
            String raw = controller.ui().readLine();
            try {
                HumanCommand command = controller.parser().parse(raw);
                if (command instanceof BuildRoadCommand) {
                    BuildRoadCommand roadCommand = (BuildRoadCommand) command;
                    Edge edge = board.getEdgeBetween(roadCommand.getFromNodeId(), roadCommand.getToNodeId());
                    if (edge != null
                            && (roadCommand.getFromNodeId() == settlementNodeId || roadCommand.getToNodeId() == settlementNodeId)
                            && board.canPlaceRoad(player.id(), edge.getId())) {
                        setupPlaceRoad(player, edge.getId());
                        log(player, "Setup road at edge " + edge.getId() + " (" + roadCommand.getFromNodeId() + "," + roadCommand.getToNodeId() + ").");
                        return edge.getId();
                    }
                }
            } catch (IllegalArgumentException ex) {
                controller.ui().printLine(ex.getMessage());
            }
            controller.ui().printLine("Invalid setup road. Try again.");
        }
    }


    private int pickRandomSetupSettlement(int playerId) {
        List<Integer> legalNodes = new ArrayList<>();
        for (int nodeId = 0; nodeId < board.getNodes().length; nodeId++) {
            if (board.canPlaceSettlement(playerId, nodeId, Phase.SETUP)) {
                legalNodes.add(nodeId);
            }
        }
        if (legalNodes.isEmpty()) {
            throw new IllegalStateException("No legal setup settlement found.");
        }
        return legalNodes.get(random.nextInt(legalNodes.size()));
    }

    private void setupPlaceSettlement(Player player, int nodeId) {
        board.placeSettlement(player.id(), nodeId);
        player.setSettlementsLeft(player.getSettlementsLeft() - 1);
        player.addVictoryPoints(1);
    }

    private void setupPlaceRoad(Player player, int edgeId) {
        board.placeRoad(player.id(), edgeId);
        player.setRoadsLeft(player.getRoadsLeft() - 1);
    }

    private void grantInitialResourcesFromNode(int playerId, int nodeId) {
        for (Tile tile : board.getTiles()) {
            if (tile.getTerrain() == Terrain.DESERT) {
                continue;
            }
            for (int adjacentNodeId : board.nodesAroundTile(tile.getId())) {
                if (adjacentNodeId == nodeId) {
                    Resource resource = tile.getResource();
                    if (bank.give(resource, 1)) {
                        players[playerId].addResource(resource, 1);
                        log(players[playerId], "Gained 1 " + resource + " from setup at tile " + tile.getId() + ".");
                    }
                    break;
                }
            }
        }
    }

    public boolean performRoll(Player player) {
        if (phase() != Phase.MAIN || stage() != TurnStage.WAIT_ROLL) {
            systemMessage("Roll is not allowed right now.");
            return false;
        }

        int roll = dice.roll();
        log(player, "Rolled " + roll + ".");
        turns.setStage(TurnStage.ACTIONS);
        if (roll == 7) {
            resolveRobber(player);
        } 
        else {
            distributeResources(roll);
        }
        writeGameState();
        return true;
    }

    //resource production method
	//distribute resources to players for a given dice roll depending on the players current settlement/city positions
    public void distributeResources(int roll) {
        for (Tile tile : board.getTiles()) {
            if (tile.getNumber() == null || tile.getNumber() != roll || tile.getTerrain() == Terrain.DESERT) {
                continue;
            }
            if (board.tileBlockedByRobber(tile.getId())) {
                continue;
            }
            for (int nodeId : board.nodesAroundTile(tile.getId())) {
                Node node = board.node(nodeId);
                if (node.empty()) {
                    continue;
                }
                int amount = node.getBuilding() == BuildingType.CITY ? 2 : 1;
                Resource resource = tile.getResource();
                if (bank.give(resource, amount)) {
                    Player receiver = players[node.getOwner()];
                    receiver.addResource(resource, amount);
                    log(receiver, "Received " + amount + " " + resource + " from tile " + tile.getId() + ".");
                }
            }
        }
    }


    public void resolveRobber(Player roller) {
        for (Player player : players) {
            if (player.totalCards() > 7) {
                int toDiscard = player.totalCards() / 2;
                Map<Resource, Integer> discarded = player.discardRandom(toDiscard, random);
                bank.receiveAll(discarded);
                log(player, "Discarded " + toDiscard + " card(s) because of a 7.");
            }
        }

        int newTile = random.nextInt(board.getTiles().length);
        board.moveRobber(newTile);
        log(roller, "Moved the robber to tile " + newTile + ".");

        Set<Integer> adjacentPlayers = board.playersAdjacentToTile(newTile);
        List<Integer> victims = new ArrayList<>();
        for (int adjacentPlayerId : adjacentPlayers) {
            if (adjacentPlayerId != roller.id() && players[adjacentPlayerId].totalCards() > 0) {
                victims.add(adjacentPlayerId);
            }
        }

        if (victims.isEmpty()) {
            log(roller, "Could not steal a card from anyone.");
            return;
        }

        Player victim = players[victims.get(random.nextInt(victims.size()))];
        Resource stolen = victim.removeRandomResource(random);
        if (stolen != null) {
            roller.addResource(stolen, 1);
            log(roller, "Stole 1 " + stolen + " from P" + victim.id() + ".");
        }
    }

    public boolean buildRoad(Player player, int edgeId) {
        if (phase() != Phase.MAIN || stage() != TurnStage.ACTIONS) {
            systemMessage("Road building is not allowed right now.");
            return false;
        }

        if (player.getRoadsLeft() <= 0 || !player.hasResources(ROAD_COST) || !board.canPlaceRoad(player.id(), edgeId)) {
            return false;
        }
        player.pay(ROAD_COST);
        bank.receiveAll(ROAD_COST);
        board.placeRoad(player.id(), edgeId);
        player.setRoadsLeft(player.getRoadsLeft() - 1);
        log(player, "Built road at edge " + edgeId + ".");
        writeGameState();
        return true;
    }

    public boolean buildRoadBetweenNodes(Player player, int fromNodeId, int toNodeId) {
        Edge edge = board.getEdgeBetween(fromNodeId, toNodeId);
        if (edge == null) {
            systemMessage("No edge exists between node " + fromNodeId + " and node " + toNodeId + ".");
            return false;
        }
        return buildRoad(player, edge.getId());
    }



    public boolean buildSettlement(Player player, int nodeId) {
        if (phase() != Phase.MAIN || stage() != TurnStage.ACTIONS) {
            systemMessage("Settlement building is not allowed right now.");
            return false;
        }
        if (player.getSettlementsLeft() <= 0 || !player.hasResources(SETTLEMENT_COST)
                || !board.canPlaceSettlement(player.id(), nodeId, phase())) {
            return false;
        }


        player.pay(SETTLEMENT_COST);
        bank.receiveAll(SETTLEMENT_COST);
        board.placeSettlement(player.id(), nodeId);
        player.setSettlementsLeft(player.getSettlementsLeft() - 1);
        player.addVictoryPoints(1);
        log(player, "Built settlement at node " + nodeId + ".");
        writeGameState();
        return true;
    }

    public boolean upgradeToCity(Player player, int nodeId) {
        if (phase() != Phase.MAIN || stage() != TurnStage.ACTIONS) {
            systemMessage("City building is not allowed right now.");
            return false;
        }
        if (player.getCitiesLeft() <= 0 || !player.hasResources(CITY_COST)
                || !board.canUpgradeToCity(player.id(), nodeId)) {
            return false;
        }

        player.pay(CITY_COST);
        bank.receiveAll(CITY_COST);
        board.upgradeToCity(player.id(), nodeId);
        player.setSettlementsLeft(player.getSettlementsLeft() + 1);
        player.setCitiesLeft(player.getCitiesLeft() - 1);
        player.addVictoryPoints(1);
        log(player, "Upgraded node " + nodeId + " to a city.");
        writeGameState();
        return true;
    }


    public void writeGameState() {
        if (stateWriter != null) {
            stateWriter.write(this);
        }
    }
}