// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class HumanController implements PlayerController {
    private final CommandParser parser;
    private final CommandLineUI ui;

    public HumanController(CommandParser parser, CommandLineUI ui) {
        this.parser = parser;
        this.ui = ui;
    }

    public CommandParser parser() {
        return parser;
    }

    public CommandLineUI ui() {
        return ui;
    }

    @Override
    public void takeTurn(Game game, Player player) {
        ui.printLine("Human turn for P" + player.id() + ". Commands: Roll, List, Build ..., Go");
        while (true) {
            ui.printLine("P" + player.id() + "> ");
            String raw = ui.readLine();
            try {
                HumanCommand command = parser.parse(raw);
                boolean success = command.execute(game, player);
                if (success && command.endsTurn()) {
                    break;
                }
            } catch (IllegalArgumentException ex) {
                ui.printLine(ex.getMessage());
            }
        }
    }
}