// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class ListCommand implements HumanCommand {
    @Override
    public boolean execute(Game game, Player player) {
        game.systemMessage("Hand: " + player.handSummary());
        return true;
    }

    @Override
    public boolean endsTurn() {
        return false;
    }
}