// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

public class Node {
    private final int id;
    private int owner = -1;
    private BuildingType building = null;

    public Node(int id) {
        this.id = id;
    }

    public boolean empty() {
        return owner == -1;
    }

    public void setBuilding(int playerId, BuildingType building) {
        this.owner = playerId;
        this.building = building;
    }

    public int getId() {
        return id;
    }

    public int getOwner() {
        return owner;
    }

    public BuildingType getBuilding() {
        return building;
    }
}