// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package com.mycompany.app;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class Player {
    private final int id;
    private final PlayerColor color;
    private final Map<Resource, Integer> hand = new EnumMap<>(Resource.class);
    private int roadsLeft = 15;
    private int settlementsLeft = 5;
    private int citiesLeft = 4;
    private int victoryPoints = 0;

    public Player(int id) {
        this(id, defaultColorFor(id));
    }

    public Player(int id, PlayerColor color) {
        this.id = id;
        this.color = color;
        for (Resource r : Resource.values()) {
            hand.put(r, 0);
        }
    }

    private static PlayerColor defaultColorFor(int id) {
        PlayerColor[] colors = {PlayerColor.RED,PlayerColor.BLUE, PlayerColor.ORANGE, PlayerColor.WHITE};
        return colors[id % colors.length];
    }

    public int id() {
        return id;
    }

    public PlayerColor color() {
        return color;
    }

    public int vp() {
        return victoryPoints;
    }


    public void addResource(Resource r, int num) {
        if (r == null || num <= 0) {
            return;
        }
        hand.put(r, hand.get(r) + num);
    }

    public boolean removeResource(Resource r, int num) {
        if (r == null || num <= 0 || hand.get(r) < num) {
            return false;
        }
        hand.put(r, hand.get(r) - num);
        return true;
    }

    public boolean hasResources(Map<Resource, Integer> cost) {
        for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
            if (hand.get(entry.getKey()) < entry.getValue()) {
                return false;
            }
        }
        return true;
    }

    public void pay(Map<Resource, Integer> cost) {
        for (Map.Entry<Resource, Integer> entry : cost.entrySet()) {
            hand.put(entry.getKey(), hand.get(entry.getKey()) - entry.getValue());
        }
    }

    public int totalCards() {
        return hand.values().stream().mapToInt(Integer::intValue).sum();
    }

    public void addVictoryPoints(int n) {
        victoryPoints += n;
    }

    public Map<Resource, Integer> handSummary() {
        return Collections.unmodifiableMap(new EnumMap<>(hand));
    }

    public Resource removeRandomResource(Random random) {
        List<Resource> choices = new ArrayList<>();
        for (Map.Entry<Resource, Integer> entry : hand.entrySet()) {
            for (int i = 0; i < entry.getValue(); i++) {
                choices.add(entry.getKey());
            }
        }
        if (choices.isEmpty()) {
            return null;
        }
        Resource chosen = choices.get(random.nextInt(choices.size()));
        hand.put(chosen, hand.get(chosen) - 1);
        return chosen;
    }


    public Map<Resource, Integer> discardRandom(int n, Random random) {
        Map<Resource, Integer> discarded = new EnumMap<>(Resource.class);
        for (Resource resource : Resource.values()) {
            discarded.put(resource, 0);
        }


        for (int i = 0; i < n; i++) {
            Resource removed = removeRandomResource(random);
            if (removed == null) {
                break;
            }
            discarded.put(removed, discarded.get(removed) + 1);
        }
        return discarded;
    }

    public int getRoadsLeft() {
        return roadsLeft;
    }

    public int getSettlementsLeft() {
        return settlementsLeft;
    }

    public int getCitiesLeft() {
        return citiesLeft;
    }

    public void setRoadsLeft(int roadsLeft) {
        this.roadsLeft = roadsLeft;
    }

    public void setSettlementsLeft(int settlementsLeft) {
        this.settlementsLeft = settlementsLeft;
    }

    public void setCitiesLeft(int citiesLeft) {
        this.citiesLeft = citiesLeft;
    }
}